on: ['push', 'pull_request']

name: test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - uses: actions/checkout@v2
      - name: dep-check
        uses: tj-actions/depcheck@v7.2
        with:
          ignores: 'eslint*,prettier,@types/node'

      - name: npm install and lint
        run: |
          npm install
          npm run lint
